export const chatSessions = [
  {
    id: "1",
    title: "Real Madrid Injuries",
    excerpt: "Snoop on Jude Bellingham. Bark when he's...",
    timestamp: "2m ago",
    active: true,
  },
  {
    id: "2",
    title: "Nvidia Stocks",
    excerpt: "Track NVDA market close price...",
    timestamp: "1d ago",
    active: false,
  },
  {
    id: "3",
    title: "F1 Lewis Hamilton",
    excerpt: "Ferrari move confirmation details...",
    timestamp: "3d ago",
    active: false,
  },
  {
    id: "4",
    title: "New M3 MacBook",
    excerpt: "Release date rumors and specs...",
    timestamp: "5d ago",
    active: false,
  },
  {
    id: "5",
    title: "Bitcoin Halving",
    excerpt: "Expected dates and market sentiment...",
    timestamp: "6d ago",
    active: false,
  },
  {
    id: "6",
    title: "Super Bowl Highlights",
    excerpt: "Key moments and reactions from fans...",
    timestamp: "1w ago",
    active: false,
  },
  {
    id: "7",
    title: "OpenAI Sora",
    excerpt: "Everything you need to know about Sora...",
    timestamp: "1w ago",
    active: false,
  },
  {
    id: "8",
    title: "Elon Musk vs OpenAI",
    excerpt: "The latest updates on the legal battle...",
    timestamp: "2w ago",
    active: false,
  },
  {
    id: "9",
    title: "Apple Vision Pro",
    excerpt: "Review of the first spatial computer...",
    timestamp: "2w ago",
    active: false,
  },
  {
    id: "10",
    title: "SpaceX Starship",
    excerpt: "Summary of the most recent test flight...",
    timestamp: "3w ago",
    active: false,
  },
];
